### ISSUE TITLE
备份扫描的bug

### ISSUE THREAD

**Issue by TheKingOfDuck** [7kbstorm/7kbscan-WebPathBrute#12]
如下图所示，当扫描的目标地址是ip而不是域名时，就会出现大量误报，建议开始扫描前识别一下是否为域名，不是就直接跳过用域名生成字典。

<img width="1153" alt="8114EDC24CCB7B9375EA4589968CA809" src="https://user-images.githubusercontent.com/27769271/61791298-2ef3fc00-ae4c-11e9-8669-b966d1106dc0.png">

**Comment by 7kbstorm** [comment]
ok
