### ISSUE TITLE
自动加载/的bug

### ISSUE THREAD

**Issue by yzddmr6** [7kbstorm/7kbscan-WebPathBrute#9]
![image](https://user-images.githubusercontent.com/46088090/59602288-f1a79a80-9138-11e9-9f71-88b02c23c9fa.png)
看到了这一条
本意是想让有些字典中开头没有 / 的加上防止报错
但是也带来一个问题
![image](https://user-images.githubusercontent.com/46088090/59602352-11d75980-9139-11e9-997d-c5cf70dc948c.png)
假如我要是对端口扫描的话
字典中是 `:7001/`
也会自动加上斜杠导致不能正常工作

个人建议:
可以增加个按钮 让用户来决定是否在url后面自动加 /

**Comment by 7kbstorm** [comment]
新版已放弃
